### ISSUE TITLE
TypeError: Cannot read properties of undefined

### ISSUE THREAD

**Issue by RomuloVitoi** [nearform/mercurius-federation-info#117]
I'm getting the following error on the /federation-schema endpoint on the latest release (0.2.6):
```
TypeError: Cannot read properties of undefined (reading 'serviceMap')
    at Object.<anonymous> (mercurius-federation-info/index.js:21:47
```

**Comment by ekynoxe** [comment]
This looks potentially related to the upgrade to mercurius 12.1.0 done in https://github.com/nearform/mercurius-federation-info/pull/112

(Mercurius changelog: https://github.com/mercurius-js/mercurius/releases/tag/v12.0.0)

**Comment by ekynoxe** [comment]
@RomuloVitoi in which scenario did you see this, by the way? What's the repro case?

I'm looking into it, and wonder if this is an issue where the `@mercurius/gateway` needs to be awaited on, somehow, as it's now been extracted from mercurius itself in the above PR / release.

@codeflyer is there a way for a plugin to wait for another one to be loaded? (I'm just building up my knowledge of fastify, so I might be missing a basic point here)

**Comment by RomuloVitoi** [comment]
@ekynoxe I saw the issue in this version bump: https://github.com/nearform/mercurius-federation-info-graphiql-plugin/pull/235
